"""Add analysis logs table

Revision ID: 9284c905d1bc
Revises: e8e442b87c15
Create Date: 2024-04-13 17:23:02.606085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9284c905d1bc'
down_revision = 'e8e442b87c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('analysis_logs')
    # ### end Alembic commands ###
