"""Initial migration.

Revision ID: 921efc3f2134
Revises: 
Create Date: 2024-04-12 23:09:57.305945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921efc3f2134'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('energy_value_min', sa.Float(), nullable=True),
    sa.Column('energy_value_max', sa.Float(), nullable=True),
    sa.Column('sodium_min', sa.Float(), nullable=True),
    sa.Column('sodium_max', sa.Float(), nullable=True),
    sa.Column('total_sugar_min', sa.Float(), nullable=True),
    sa.Column('total_sugar_max', sa.Float(), nullable=True),
    sa.Column('free_sugars_min', sa.Float(), nullable=True),
    sa.Column('free_sugars_max', sa.Float(), nullable=True),
    sa.Column('total_protein_min', sa.Float(), nullable=True),
    sa.Column('total_protein_max', sa.Float(), nullable=True),
    sa.Column('total_fat_min', sa.Float(), nullable=True),
    sa.Column('total_fat_max', sa.Float(), nullable=True),
    sa.Column('fruit_content_min', sa.Float(), nullable=True),
    sa.Column('fruit_content_max', sa.Float(), nullable=True),
    sa.Column('age_marking_min', sa.Float(), nullable=True),
    sa.Column('age_marking_max', sa.Float(), nullable=True),
    sa.Column('high_sugar_front_packaging_min', sa.Float(), nullable=True),
    sa.Column('high_sugar_front_packaging_max', sa.Float(), nullable=True),
    sa.Column('labeling_requirements', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('analysis_date_time', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elements')
    op.drop_table('categories')
    # ### end Alembic commands ###
