"""Add Characteristic.

Revision ID: e8e442b87c15
Revises: 921efc3f2134
Create Date: 2024-04-12 23:36:26.421592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e442b87c15'
down_revision = '921efc3f2134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('energy_value', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('total_sugar', sa.Float(), nullable=True),
    sa.Column('free_sugars', sa.Float(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('fruit_content', sa.Float(), nullable=True),
    sa.Column('age_marking', sa.Float(), nullable=True),
    sa.Column('high_sugar_front_packaging', sa.Float(), nullable=True),
    sa.Column('labeling', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('element_characteristics')
    # ### end Alembic commands ###
